import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>FUDY</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Logo.png" />
      </Head>
      {/* body */}
      <main>
        <h1>hello</h1>
      </main>
    </div>
  );
};

export default Home;
