import type { NextPage } from "next";
import Head from "next/head";
import Hero from "../components/Hero";
import Layout from "../components/Layout";
import Services from "../components/Services";
import { client } from "../lib/client";
import css from "../styles/Home.module.css";

import { Pizza } from "../sanity-backend/schemaTypes";
import Menu from "../components/Menu";

interface IProps {
  pizzas: Pizza[];
}

const Home = ({ pizzas }: IProps) => {
  return (
    <Layout>
      <div className={css.container}>
        <Head>
          <title>FUDY</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/Logo.png" />
        </Head>
        {/* body */}
        <main>
          <Hero />
          <Services />
          <Menu pizzas={pizzas} />
        </main>
      </div>
    </Layout>
  );
};

export default Home;

export const getServerSideProps = async () => {
  const query = "*[_type == 'pizza']";
  const pizzas = await client.fetch<Pizza[]>(query);
  return {
    props: {
      pizzas,
    },
  };
};
